version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: my_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - rental_company_db:/var/lib/mysql
    networks:
      - backend_rental_company
  app:
    build: .
    container_name: php
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - backend_rental_company

volumes:
  rental_company_db:
    name: rental_company_db
    driver: local

networks:
  backend_rental_company:
    name: backend_rental_company
    driver: bridge
