version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: my_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3305:3306"
    volumes:
      - database_rental:/var/lib/mysql
    networks:
      - back_rental
  app:
    build: .
    container_name: php
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    networks:
      - back_rental

volumes:
  database_rental:
    name: database_rental
    driver: local

networks:
  back_rental:
    name: back_rental
    driver: bridge
